name: Continuous-Double-Auctions
main: com.broscraft.cda.CDAPlugin
version: 0.0.1
api-version: 1.16
softdepend: [Vault, Essentials]
commands:
  market:
    description: Open the market GUI.
    usage: /<command>
    aliases: ['m']
  searchmarket:
    description: Searches the market for items matching a provided query.
    usage: /<command> 'item name'
    aliases: ['sm']
  neworder:
    description: Create a new order.
    usage: /<command> [bid | ask] <price> <quantity>
    aliases: ['no']