name: ContinuousDoubleAuctions
main: com.broscraft.cda.CDAPlugin
version: 0.0.1
api-version: 1.16
softdepend: [Vault, Essentials]
commands:
  market:
    description: Open the market GUI. Add argument 'this' to open orders page for item in hand.
    usage: /<command> [this]
    aliases: ['mkt']
  myorders:
    description: Open your orders screen.
    usage: /<command>
    aliases: ['mo']
  searchmarket:
    description: Searches the market for items matching a provided query.
    usage: /<command> 'item name'
    aliases: ['sm']
  neworder:
    description: Create a new order.
    usage: /<command> [bid | ask]
    aliases: ['no']